
-- Remove rappers that are NOT in the provided list
DELETE FROM public.rappers WHERE name NOT IN (
  '2 Chainz', '50 Cent', '8Ball & MJG', 'A Boogie wit da Hoodie', 'A Tribe Called Quest',
  'A$AP Ferg', 'A$AP Rocky', 'Ab-Soul', 'Action Bronson', 'Aesop Rock', 'André 3000',
  'Asher Roth', 'AZ', 'Azealia Banks', 'Baby Keem', 'Beanie Sigel', 'Benny the Butcher',
  'Big Boi', 'Big Daddy Kane', 'Big KRIT', 'Big L', 'Big Pun', 'Big Sean', 'BigXThaPlug',
  'Black Thought', 'Blu', 'Blueface', 'Bone Thugs-N-Harmony', 'Boosie Badazz', 'Bow Wow',
  'Busta Rhymes', 'Cam''ron', 'Canibus', 'Cardi B', 'Cassidy', 'CeeLo Green', 'Chance The Rapper',
  'Chief Keef', 'Chika', 'Childish Gambino', 'Chubb Rock', 'Clipse', 'Coast Contra',
  'Coi Leray', 'Common', 'Cordae', 'Crooked I', 'Crucial Conflict', 'Cypress Hill',
  'DaBaby', 'David Banner', 'Daylyt', 'De La Soul', 'Del the Funky Homosapien', 'Denzel Curry',
  'Digital Underground', 'Dilated Peoples', 'DMX', 'Doechii', 'E-40', 'Earl Sweatshirt',
  'EARTHGANG', 'Elzhi', 'Eminem', 'Eve', 'Fabolous', 'Fashawn', 'Fat Joe', 'Flo Milli',
  'Foxy Brown', 'Freddie Gibbs', 'Freeway', 'Future', 'Gangsta Boo', 'Ghostface Killah',
  'GloRilla', 'Goodie Mob', 'Grafh', 'Grandmaster Flash', 'Gucci Mane', 'Gunna', 'GZA',
  'Heavy D', 'Hieroglyphics', 'Hit-Boy', 'Homeboy Sandman', 'Hopsin', 'Ice Cube', 'Ice Spice',
  'Ice-T', 'Immortal Technique', 'J Dilla', 'J-Live', 'J. Cole', 'J.I.D', 'Jay Electronica',
  'Jay-Z', 'Jean Grae', 'Jeezy', 'Jim Jones', 'Joe Budden', 'Joell Ortiz', 'Joey Bada$$',
  'Jon Connor', 'JT', 'Juelz Santana', 'Juvenile', 'Kamaiyah', 'Kanye West', 'Kari Faux',
  'Keith Murray', 'Kemba', 'Ken Carson', 'Kendrick Lamar', 'Kenny Mason', 'Kid Cudi',
  'Killer Mike', 'King Los', 'Kodak Black', 'Kool G Rap', 'KRS-One', 'Kurupt', 'Lady London',
  'Ladybug Mecca', 'Lakeyah', 'LaRussell', 'Latto', 'Lauryn Hill', 'Leikeli47', 'Lil Baby',
  'Lil Dicky', 'Lil Flip', 'Lil Jon', 'Lil Kim', 'Lil Scrappy', 'Lil Tecca', 'Lil Uzi Vert',
  'Lil Wayne', 'Little Brother', 'LL Cool J', 'Logic', 'Lola Brooke', 'Ludacris', 'Lupe Fiasco',
  'Mac Dre', 'Mac Miller', 'Mach-Hommy', 'Masta Ace', 'Master P', 'MC Breed', 'MC Eiht',
  'MC Lyte', 'MC Shan', 'Megan Thee Stallion', 'Method Man', 'MF DOOM', 'Mickey Factz',
  'Missy Elliott', 'Monie Love', 'Mos Def', 'Mystikal', 'N.O.R.E.', 'Nas', 'Naughty By Nature',
  'Nelly', 'Nicki Minaj', 'Nipsey Hussle', 'Noname', 'OJ Da Juiceman', 'Ol'' Dirty Bastard',
  'Open Mike Eagle', 'Oswin Benjamin', 'Outkast', 'Papoose', 'Pharoahe Monch', 'Playboi Carti',
  'Project Pat', 'Public Enemy', 'Pusha T', 'Q-Tip', 'Queen Latifah', 'Raekwon', 'Rah Digga',
  'Rakim', 'Rapsody', 'Ras Kass', 'Redman', 'Remy Ma', 'Rhymefest', 'Rick Ross', 'Rico Nasty',
  'Roxxane Shanté', 'Royce da 5''9"', 'Run-DMC', 'RZA', 'Sa-Roc', 'Saba', 'Sada Baby',
  'Saigon', 'Salt & Pepa', 'Sammus', 'Schoolboy Q', 'Sean Price', 'Shawty Lo', 'Silkk the Shocker',
  'Ski Mask the Slump God', 'Slick Rick', 'Slim Thug', 'Slum Village', 'Smino', 'Snoop Dogg',
  'Soulja Boy', 'Souls of Mischief', 'Styles P', 'T.I.', 'Talib Kweli', 'Tech N9ne', 'The D.O.C.',
  'The Fugees', 'The Game', 'The Notorious B.I.G.', 'The Pharcyde', 'Three 6 Mafia', 'Tierra Whack',
  'Tobe Nwigwe', 'Too $hort', 'Travis Scott', 'Trina', 'Tupac Shakur', 'Twista', 'Tyler, The Creator',
  'UGK', 'Uncle Murda', 'Vince Staples', 'Waka Flocka Flame', 'Wale', 'Webbie', 'Westside Boogie',
  'Westside Gunn', 'Will Smith', 'Wiz Khalifa', 'Wu-Tang Clan', 'XXXTENTACION', 'Xzibit',
  'Yeat', 'Yelawolf', 'YG', 'Young M.A', 'Young Thug', 'Yung Miami'
);

-- Handle name variations for existing rappers
UPDATE public.rappers SET name = 'Tupac Shakur' WHERE name = '2Pac';

-- Insert missing rappers from the list
INSERT INTO public.rappers (name, real_name, origin, birth_year, birth_month, birth_day, bio, verified) VALUES
('2 Chainz', 'Tauheed K. Epps', 'College Park, Georgia', 1977, 9, 12, 'Atlanta rapper known for his distinctive voice and trap music style.', false),
('8Ball & MJG', null, 'Memphis, Tennessee', null, null, null, 'Memphis rap duo known for their Southern hip hop style and influence on Southern rap.', false),
('A Boogie wit da Hoodie', 'Artist Julius Dubose', 'The Bronx, New York', 1995, 12, 6, 'Bronx rapper known for his melodic rap style and auto-tuned vocals.', false),
('A Tribe Called Quest', null, 'Queens, New York', null, null, null, 'Legendary hip hop group known for their jazz-influenced alternative hip hop sound.', false),
('A$AP Rocky', 'Rakim Athelaston Mayers', 'Harlem, New York', 1988, 10, 3, 'Harlem rapper known for his fashion sense and unique flow.', false),
('Ab-Soul', 'Herbert Anthony Stevens IV', 'Carson, California', 1987, 2, 23, 'TDE rapper known for his complex lyricism and conspiracy theories.', false),
('Asher Roth', 'Asher Paul Roth', 'Morrisville, Pennsylvania', 1985, 8, 11, 'Pennsylvania rapper known for his college-themed rap music.', false),
('AZ', 'Anthony Cruz', 'Brooklyn, New York', 1972, 3, 9, 'Brooklyn rapper known for his smooth flow and vivid storytelling.', false),
('Azealia Banks', 'Azealia Amanda Banks', 'Harlem, New York', 1991, 5, 31, 'Harlem rapper known for her provocative lyrics and electronic-influenced sound.', false),
('Baby Keem', 'Hykeem Jamaal Carter Jr.', 'Las Vegas, Nevada', 2000, 10, 22, 'Las Vegas rapper and Kendrick Lamar''s cousin, known for his melodic trap style.', false),
('Beanie Sigel', 'Dwight Equan Grant', 'Philadelphia, Pennsylvania', 1974, 3, 6, 'Philadelphia rapper known for his association with Roc-A-Fella Records.', false),
('Benny the Butcher', 'Jeremie Damon Pennick', 'Buffalo, New York', 1984, 11, 27, 'Buffalo rapper known for his grimy East Coast rap style and Griselda Records.', false),
('Big Daddy Kane', 'Antonio Hardy', 'Brooklyn, New York', 1968, 9, 10, 'Brooklyn rapper known as one of the most skilled MCs of the golden age.', false),
('Big KRIT', 'Justin Lewis Scott', 'Meridian, Mississippi', 1986, 8, 26, 'Mississippi rapper and producer known for his Southern sound and live instrumentation.', false),
('Big L', 'Lamont Coleman', 'Harlem, New York', 1974, 5, 30, 'Harlem rapper known for his wordplay and punchlines, considered one of the best lyricists.', false),
('Big Pun', 'Christopher Lee Rios', 'The Bronx, New York', 1971, 11, 10, 'Bronx rapper known for his complex wordplay and being the first Latino rapper to go platinum.', false),
('BigXThaPlug', 'Xavier Landum', 'Dallas, Texas', 1998, 9, 28, 'Dallas rapper known for his energetic style and Texas rap sound.', false),
('Blu', 'Johnson Barnes III', 'Los Angeles, California', 1983, 4, 15, 'Los Angeles underground rapper known for his collaboration with producer Exile.', false),
('Blueface', 'Johnathan Jamall Porter', 'Los Angeles, California', 1997, 1, 20, 'Los Angeles rapper known for his unique off-beat rapping style.', false),
('Bone Thugs-N-Harmony', null, 'Cleveland, Ohio', null, null, null, 'Cleveland rap group known for their rapid-fire harmonizing vocals and Midwest sound.', false),
('Boosie Badazz', 'Torrence Ivy Hatch Jr.', 'Baton Rouge, Louisiana', 1982, 11, 14, 'Louisiana rapper known for his Southern rap style and street narratives.', false),
('Bow Wow', 'Shad Gregory Moss', 'Columbus, Ohio', 1987, 3, 9, 'Columbus rapper who started as a child performer and became a teen rap star.', false),
('Cam''ron', 'Cameron Ezike Giles', 'Harlem, New York', 1976, 2, 4, 'Harlem rapper known for his flashy style and Diplomats group.', false),
('Canibus', 'Germaine Williams', 'Jamaica, Queens', 1974, 12, 9, 'Queens rapper known for his complex lyricism and battle rap skills.', false),
('Cassidy', 'Barry Adrian Reese', 'Philadelphia, Pennsylvania', 1982, 7, 7, 'Philadelphia rapper known for his battle rap skills and freestyle ability.', false),
('CeeLo Green', 'Thomas DeCarlo Callaway-Burton', 'Atlanta, Georgia', 1975, 5, 30, 'Atlanta rapper and singer known for Goodie Mob and his soulful voice.', false),
('Chief Keef', 'Keith Farrelle Cozart', 'Chicago, Illinois', 1995, 8, 15, 'Chicago rapper known for pioneering the drill music movement.', false),
('Chika', 'Jane Chika Oranika', 'Montgomery, Alabama', 1997, 3, 9, 'Alabama rapper known for her clever wordplay and social media presence.', false),
('Chubb Rock', 'Richard Anthony Simpson', 'Jamaica, Queens', 1968, 5, 28, 'Queens rapper known for his positive message rap and Golden Age contributions.', false),
('Clipse', null, 'Virginia Beach, Virginia', null, null, null, 'Virginia rap duo known for their cocaine rap narratives and Neptunes production.', false),
('Coast Contra', null, 'Los Angeles, California', null, null, null, 'Los Angeles rap group known for their lyrical prowess and group dynamics.', false),
('Coi Leray', 'Coi Leray Collins', 'Boston, Massachusetts', 1997, 5, 11, 'Boston rapper known for her melodic rap style and social media presence.', false),
('Cordae', 'Cordae Amari Dunston', 'Raleigh, North Carolina', 1997, 8, 26, 'North Carolina rapper known for his conscious rap and lyrical ability.', false),
('Crooked I', 'Dominick Antron Wickliffe', 'Long Beach, California', 1978, 9, 23, 'Long Beach rapper known for his technical rap skills and Slaughterhouse group.', false),
('Crucial Conflict', null, 'Chicago, Illinois', null, null, null, 'Chicago rap group known for their Midwest harmonizing style.', false),
('Cypress Hill', null, 'South Gate, California', null, null, null, 'California rap group known for their Latino identity and cannabis advocacy.', false),
('David Banner', 'Lavell William Crump', 'Brookhaven, Mississippi', 1974, 4, 11, 'Mississippi rapper and producer known for his Southern rap production.', false),
('Daylyt', 'Terelle Smith', 'Watts, California', 1987, 5, 21, 'California battle rapper known for his creative wordplay and unpredictable style.', false),
('De La Soul', null, 'Amityville, New York', null, null, null, 'Long Island rap trio known for their innovative sampling and positive messages.', false),
('Del the Funky Homosapien', 'Teren Delvon Jones', 'Oakland, California', 1972, 8, 12, 'Oakland rapper known for his alternative hip hop style and Hieroglyphics crew.', false),
('Digital Underground', null, 'Oakland, California', null, null, null, 'Oakland rap group known for their funk-influenced sound and launching Tupac''s career.', false),
('Dilated Peoples', null, 'Los Angeles, California', null, null, null, 'Los Angeles underground hip hop group known for their conscious lyrics.', false),
('Doechii', 'Jaylah Ji''mya Hickmon', 'Tampa, Florida', 1998, 8, 12, 'Florida rapper known for her versatile style and creative visuals.', false),
('E-40', 'Earl Tywone Stevens Sr.', 'Vallejo, California', 1967, 11, 15, 'California rapper known for his unique slang and Bay Area hip hop influence.', false),
('Earl Sweatshirt', 'Thebe Neruda Kgositsile', 'Chicago, Illinois', 1994, 2, 24, 'Chicago-born rapper known for his introspective lyrics and Odd Future collective.', false),
('EARTHGANG', null, 'Atlanta, Georgia', null, null, null, 'Atlanta rap duo known for their alternative Southern hip hop style.', false),
('Elzhi', 'Jason Powers', 'Detroit, Michigan', 1978, 5, 12, 'Detroit rapper known for his complex lyricism and Slum Village membership.', false),
('Fabolous', 'John David Jackson', 'Brooklyn, New York', 1977, 11, 18, 'Brooklyn rapper known for his smooth flow and street narratives.', false),
('Fashawn', 'Santiago Leyva', 'Fresno, California', 1988, 10, 19, 'California rapper known for his conscious West Coast hip hop style.', false),
('Fat Joe', 'Joseph Antonio Cartagena', 'The Bronx, New York', 1970, 8, 19, 'Bronx rapper known for his Terror Squad group and Latin hip hop influence.', false),
('Flo Milli', 'Tamia Monique Carter', 'Mobile, Alabama', 2000, 1, 9, 'Alabama rapper known for her confident delivery and viral social media presence.', false),
('Foxy Brown', 'Inga DeCarlo Fung Marchand', 'Brooklyn, New York', 1978, 9, 6, 'Brooklyn rapper known for her hardcore female rap style and 90s prominence.', false),
('Freddie Gibbs', 'Fredrick Jamel Tipton', 'Gary, Indiana', 1982, 6, 14, 'Indiana rapper known for his gangsta rap style and collaborations with Madlib.', false),
('Freeway', 'Leslie Edward Pridgen', 'Philadelphia, Pennsylvania', 1978, 8, 6, 'Philadelphia rapper known for his association with Roc-A-Fella Records.', false),
('Gangsta Boo', 'Lola Chantrelle Mitchell', 'Memphis, Tennessee', 1979, 8, 7, 'Memphis rapper known for her membership in Three 6 Mafia and hardcore style.', false),
('GloRilla', 'Gloria Hallelujah Woods', 'Memphis, Tennessee', 1999, 7, 28, 'Memphis rapper known for her energetic style and viral hits.', false),
('Goodie Mob', null, 'Atlanta, Georgia', null, null, null, 'Atlanta rap group known for their conscious Southern hip hop and Dungeon Family collective.', false),
('Grafh', 'Philip Bernard', 'Jamaica, Queens', 1982, 1, 3, 'Queens rapper known for his mixtape series and East Coast underground scene.', false),
('Grandmaster Flash', 'Joseph Saddler', 'Barbados', 1958, 1, 1, 'Barbados-born DJ and rapper, pioneer of hip hop turntablism.', false),
('Heavy D', 'Dwight Arrington Myers', 'Mandeville, Jamaica', 1967, 5, 24, 'Jamaican-American rapper known for his positive rap style and Heavy D & the Boyz.', false),
('Hieroglyphics', null, 'Oakland, California', null, null, null, 'Oakland underground hip hop collective known for their alternative style.', false),
('Hit-Boy', 'Chauncey Alexander Hollis Jr.', 'Fontana, California', 1987, 5, 21, 'California producer and rapper known for his production work with major artists.', false),
('Homeboy Sandman', 'Angel Del Villar II', 'Queens, New York', 1980, 9, 24, 'Queens rapper known for his conscious lyrics and independent hip hop approach.', false),
('Ice Spice', 'Isis Naija Gaston', 'The Bronx, New York', 2000, 1, 1, 'Bronx rapper known for her drill-influenced style and viral social media presence.', false),
('Ice-T', 'Tracy Lauren Marrow', 'Newark, New Jersey', 1958, 2, 16, 'Newark rapper known for pioneering gangsta rap and his acting career.', false),
('Immortal Technique', 'Felipe Andres Coronel', 'Lima, Peru', 1978, 2, 19, 'Peruvian-American rapper known for his revolutionary political lyrics.', false),
('J Dilla', 'James Dewitt Yancey', 'Detroit, Michigan', 1974, 2, 7, 'Detroit producer known for his innovative beats and influence on hip hop production.', false),
('J-Live', 'Justice Allah', 'Columbus, Ohio', 1976, 2, 11, 'Ohio rapper known for his conscious lyrics and independent hip hop approach.', false),
('Jay Electronica', 'Timothy Elpadaro Thedford', 'New Orleans, Louisiana', 1976, 9, 19, 'New Orleans rapper known for his mystical lyrics and sparse discography.', false),
('Jean Grae', 'Tsidi Ibrahim', 'Cape Town, South Africa', 1976, 11, 26, 'South African-born rapper known for her complex lyricism and independent approach.', false),
('Jim Jones', 'Joseph Guillermo Jones II', 'The Bronx, New York', 1976, 7, 15, 'Bronx rapper known for his Diplomats membership and East Coast hip hop.', false),
('Joe Budden', 'Joseph Anthony Budden II', 'Spanish Harlem, New York', 1980, 8, 31, 'New York rapper known for his emotional lyrics and media personality.', false),
('Joell Ortiz', 'Joell Christopher Ortiz', 'Brooklyn, New York', 1980, 7, 6, 'Brooklyn rapper known for his Slaughterhouse membership and Puerto Rican heritage.', false),
('Jon Connor', 'Jon Kevin Freeman Jr.', 'Flint, Michigan', 1985, 4, 17, 'Michigan rapper known for his conscious lyrics and Aftermath Entertainment signing.', false),
('JT', 'Jatavia Shakara Johnson', 'Miami, Florida', 1992, 12, 3, 'Miami rapper known for her City Girls membership and Southern hip hop style.', false),
('Juelz Santana', 'LaRon Louis James Sr.', 'Harlem, New York', 1982, 2, 18, 'Harlem rapper known for his Diplomats membership and melodic rap style.', false),
('Juvenile', 'Terius Gray', 'New Orleans, Louisiana', 1975, 3, 25, 'New Orleans rapper known for his bounce music influence and Cash Money Records.', false),
('Kamaiyah', 'Kamaiyah Jamesha Johnson', 'Oakland, California', 1992, 3, 13, 'Oakland rapper known for her Bay Area hip hop style and melodic approach.', false),
('Kari Faux', 'Kari Johnson', 'Little Rock, Arkansas', 1992, 7, 8, 'Arkansas rapper known for her alternative hip hop style and independent approach.', false),
('Keith Murray', 'Keith Omar Murray', 'Central Islip, New York', 1974, 9, 13, 'New York rapper known for his complex wordplay and Def Squad membership.', false),
('Kemba', 'Kemba Walker', 'The Bronx, New York', 1990, 11, 10, 'Bronx rapper known for his conscious lyrics and jazz-influenced sound.', false),
('Ken Carson', 'Kenyatta Lee Frazier Jr.', 'Atlanta, Georgia', 2000, 4, 11, 'Atlanta rapper known for his association with Playboi Carti and rage rap style.', false),
('Kenny Mason', 'Kenny Mason', 'Atlanta, Georgia', 1995, 6, 17, 'Atlanta rapper known for his alternative hip hop style and rock influences.', false),
('King Los', 'Carlos Coleman', 'Baltimore, Maryland', 1982, 3, 23, 'Baltimore rapper known for his freestyle ability and rapid-fire delivery.', false),
('Kool G Rap', 'Nathaniel Thomas Wilson', 'Corona, Queens', 1968, 7, 20, 'Queens rapper known as one of the most influential MCs in hip hop history.', false),
('KRS-One', 'Lawrence Parker', 'The Bronx, New York', 1965, 8, 20, 'Bronx rapper known for his conscious lyrics and "Teacher" persona.', false),
('Kurupt', 'Ricardo Emmanuel Brown', 'Philadelphia, Pennsylvania', 1972, 11, 23, 'Philadelphia rapper known for his Dogg Pound membership and West Coast style.', false),
('Lady London', 'Zaire Stewart', 'Harlem, New York', 1995, 9, 5, 'Harlem rapper known for her lyrical ability and female empowerment themes.', false),
('Ladybug Mecca', 'Mary Ann Vieira', 'Silver Spring, Maryland', 1973, 7, 25, 'Maryland rapper known for her Digable Planets membership and jazz rap style.', false),
('Lakeyah', 'Lakeyah Danaee Robinson', 'Milwaukee, Wisconsin', 2001, 2, 28, 'Wisconsin rapper known for her melodic rap style and young success.', false),
('LaRussell', 'Russell Santiago', 'Vallejo, California', 1987, 2, 14, 'California rapper known for his independent approach and Bay Area sound.', false),
('Latto', 'Alyssa Michelle Stephens', 'Columbus, Ohio', 1998, 12, 22, 'Ohio-born rapper known for her Southern style and reality TV background.', false),
('Leikeli47', 'Hasben Jones', 'Virginia', 1990, 1, 1, 'Virginia rapper known for her masked persona and alternative hip hop style.', false),
('Lil Dicky', 'David Andrew Burd', 'Cheltenham Township, Pennsylvania', 1988, 3, 15, 'Pennsylvania rapper known for his comedic approach to hip hop.', false),
('Lil Flip', 'Wesley Eric Weston Jr.', 'Houston, Texas', 1981, 3, 3, 'Houston rapper known for his Southern rap style and freestyle ability.', false),
('Lil Kim', 'Kimberly Denise Jones', 'Brooklyn, New York', 1974, 7, 11, 'Brooklyn rapper known for her hardcore style and Junior M.A.F.I.A. membership.', false),
('Lil Scrappy', 'Darryl Raynard Richardson III', 'Atlanta, Georgia', 1984, 1, 19, 'Atlanta rapper known for his crunk music style and reality TV appearances.', false),
('Lil Tecca', 'Tyler-Justin Anthony Sharpe', 'Queens, New York', 2002, 8, 26, 'Queens rapper known for his melodic rap style and young success.', false),
('Little Brother', null, 'Durham, North Carolina', null, null, null, 'North Carolina rap group known for their conscious Southern hip hop style.', false),
('LL Cool J', 'James Todd Smith', 'Bay Shore, New York', 1968, 1, 14, 'New York rapper known as one of hip hop''s first superstars and acting career.', false),
('Lola Brooke', 'Shyniece Thomas', 'Brooklyn, New York', 1994, 2, 1, 'Brooklyn rapper known for her drill-influenced style and New York sound.', false),
('Mac Dre', 'Andre Louis Hicks', 'Oakland, California', 1970, 7, 5, 'Oakland rapper known for his hyphy movement influence and Bay Area sound.', false),
('Mach-Hommy', 'Mach-Hommy', 'Newark, New Jersey', 1977, 8, 24, 'Newark rapper known for his abstract lyricism and underground approach.', false),
('Masta Ace', 'Duval Clear', 'Brownsville, Brooklyn', 1966, 12, 4, 'Brooklyn rapper known for his storytelling ability and Juice Crew membership.', false),
('Master P', 'Percy Robert Miller Sr.', 'New Orleans, Louisiana', 1967, 4, 29, 'New Orleans rapper and entrepreneur known for No Limit Records empire.', false),
('MC Breed', 'Eric Tyrone Breed', 'Flint, Michigan', 1971, 6, 12, 'Michigan rapper known for his Midwest hip hop style and independent success.', false),
('MC Eiht', 'Aaron Bernard Tyler', 'Compton, California', 1971, 5, 22, 'Compton rapper known for his gangsta rap style and Compton''s Most Wanted.', false),
('MC Lyte', 'Lana Michele Moorer', 'Brooklyn, New York', 1970, 10, 11, 'Brooklyn rapper known as one of the first successful female MCs.', false),
('MC Shan', 'Shawn Moltke', 'Queensbridge, New York', 1965, 9, 6, 'Queens rapper known for his Juice Crew membership and "The Bridge" controversy.', false),
('Mickey Factz', 'Marcus Aureus', 'The Bronx, New York', 1982, 11, 24, 'Bronx rapper known for his lyrical ability and independent approach.', false),
('Monie Love', 'Simone Gooden', 'London, England', 1970, 7, 2, 'British rapper known for her UK hip hop influence and international success.', false),
('Mystikal', 'Michael Lawrence Tyler', 'New Orleans, Louisiana', 1970, 9, 22, 'New Orleans rapper known for his energetic delivery and Southern style.', false),
('N.O.R.E.', 'Victor James Santiago Jr.', 'Queens, New York', 1977, 9, 6, 'Queens rapper known for his Capone-N-Noreaga membership and Latin hip hop.', false),
('Naughty By Nature', null, 'East Orange, New Jersey', null, null, null, 'New Jersey rap trio known for their hit "Hip Hop Hooray" and positive messages.', false),
('Noname', 'Fatimah Nyeema Warner', 'Chicago, Illinois', 1991, 9, 18, 'Chicago rapper known for her jazz-influenced sound and conscious lyrics.', false),
('OJ Da Juiceman', 'Otis Williams Jr.', 'Atlanta, Georgia', 1981, 11, 23, 'Atlanta rapper known for his trap music style and Gucci Mane association.', false),
('Ol'' Dirty Bastard', 'Russell Tyrone Jones', 'Brooklyn, New York', 1968, 11, 15, 'Brooklyn rapper known for his Wu-Tang Clan membership and eccentric personality.', false),
('Open Mike Eagle', 'Michael Eagle II', 'Chicago, Illinois', 1980, 6, 13, 'Chicago rapper known for his alternative hip hop style and comedy background.', false),
('Oswin Benjamin', 'Oswin Benjamin', 'Richmond, Virginia', 1991, 3, 19, 'Virginia rapper known for his conscious lyrics and independent approach.', false),
('Outkast', null, 'Atlanta, Georgia', null, null, null, 'Atlanta rap duo known for their innovative Southern hip hop style and mainstream success.', false),
('Papoose', 'Shamele Mackie', 'Brooklyn, New York', 1978, 3, 5, 'Brooklyn rapper known for his complex wordplay and mixtape series.', false),
('Pharoahe Monch', 'Troy Donald Jamerson', 'South Jamaica, Queens', 1972, 10, 31, 'Queens rapper known for his complex lyricism and Organized Konfusion membership.', false),
('Project Pat', 'Patrick Earl Houston', 'Memphis, Tennessee', 1973, 2, 8, 'Memphis rapper known for his Three 6 Mafia association and crunk style.', false),
('Public Enemy', null, 'Roosevelt, New York', null, null, null, 'New York rap group known for their political messages and innovative production.', false),
('Pusha T', 'Terrence LeVarr Thornton', 'The Bronx, New York', 1977, 5, 13, 'Bronx-born rapper known for his Clipse membership and cocaine rap narratives.', false),
('Q-Tip', 'Kamaal Ibn John Fareed', 'Harlem, New York', 1970, 4, 10, 'Harlem rapper known for his A Tribe Called Quest leadership and jazz influence.', false),
('Queen Latifah', 'Dana Elaine Owens', 'Newark, New Jersey', 1970, 3, 18, 'Newark rapper known for her positive female empowerment messages and acting career.', false),
('Raekwon', 'Corey Woods', 'Brooklyn, New York', 1970, 1, 12, 'Brooklyn rapper known for his Wu-Tang Clan membership and mafioso rap style.', false),
('Rah Digga', 'Rashia Tashan Fisher', 'Newark, New Jersey', 1974, 12, 18, 'Newark rapper known for her Flipmode Squad membership and hardcore style.', false),
('Rakim', 'William Michael Griffin Jr.', 'Wyandanch, New York', 1968, 1, 28, 'New York rapper known as one of the most influential MCs in hip hop history.', false),
('Rapsody', 'Marlanna Evans', 'Snow Hill, North Carolina', 1983, 1, 21, 'North Carolina rapper known for her conscious lyrics and Southern sound.', false),
('Ras Kass', 'John R. Austin II', 'Carson, California', 1973, 9, 26, 'California rapper known for his complex lyricism and underground approach.', false),
('Redman', 'Reginald Noble', 'Newark, New Jersey', 1970, 4, 17, 'Newark rapper known for his wild style and Method Man collaborations.', false),
('Remy Ma', 'Reminisce Mackie', 'Castle Hill, Bronx', 1980, 5, 30, 'Bronx rapper known for her Terror Squad membership and hardcore style.', false),
('Rhymefest', 'Che Jami Smith', 'Chicago, Illinois', 1977, 7, 6, 'Chicago rapper known for his conscious lyrics and Grammy-winning songwriting.', false),
('Rico Nasty', 'Maria-Cecilia Simone Kelly', 'New York City, New York', 1997, 5, 7, 'New York rapper known for her punk-influenced rap style and colorful aesthetic.', false),
('Roxxane Shanté', 'Lolita Shanté Gooden', 'Queensbridge, New York', 1969, 11, 9, 'Queens rapper known as one of the first successful female MCs and battle rapper.', false),
('Royce da 5''9"', 'Ryan Daniel Montgomery', 'Detroit, Michigan', 1977, 7, 5, 'Detroit rapper known for his lyrical ability and Bad Meets Evil partnership.', false),
('Run-DMC', null, 'Hollis, Queens', null, null, null, 'Queens rap group known for bringing hip hop to mainstream audiences in the 1980s.', false),
('RZA', 'Robert Fitzgerald Diggs', 'Brownsville, Brooklyn', 1969, 7, 5, 'Brooklyn rapper known as Wu-Tang Clan''s leader and main producer.', false),
('Sa-Roc', 'Assata Perkins', 'Washington, D.C.', 1982, 10, 28, 'D.C. rapper known for her conscious lyrics and independent approach.', false),
('Saba', 'Tahj Malik Chandler', 'Chicago, Illinois', 1994, 7, 17, 'Chicago rapper known for his conscious lyrics and jazz-influenced sound.', false),
('Sada Baby', 'Casada Aaron Sorrell', 'Detroit, Michigan', 1992, 11, 17, 'Detroit rapper known for his aggressive style and Michigan hip hop sound.', false),
('Saigon', 'Brian Daniel Carenard', 'Brooklyn, New York', 1977, 7, 13, 'Brooklyn rapper known for his conscious lyrics and street narratives.', false),
('Salt & Pepa', null, 'Queens, New York', null, null, null, 'Queens rap duo known as one of the first successful all-female rap groups.', false),
('Sammus', 'Enongo Lumumba-Kasongo', 'Ithaca, New York', 1986, 10, 15, 'New York rapper known for her nerdcore hip hop style and academic background.', false),
('Sean Price', 'Sean Duval Price', 'Brooklyn, New York', 1972, 3, 17, 'Brooklyn rapper known for his Heltah Skeltah membership and hardcore style.', false),
('Shawty Lo', 'Carlos Rico Walker', 'Atlanta, Georgia', 1976, 3, 22, 'Atlanta rapper known for his crunk music style and D4L membership.', false),
('Silkk the Shocker', 'Vyshonn King Miller', 'New Orleans, Louisiana', 1975, 6, 18, 'New Orleans rapper known for his No Limit Records association and Southern style.', false),
('Slick Rick', 'Richard Martin Lloyd Walters', 'Mitcham, London', 1965, 1, 14, 'British-American rapper known for his storytelling ability and distinctive voice.', false),
('Slim Thug', 'Stayve Jerome Thomas', 'Houston, Texas', 1980, 9, 8, 'Houston rapper known for his Southern rap style and tall stature.', false),
('Slum Village', null, 'Detroit, Michigan', null, null, null, 'Detroit hip hop group known for their soulful production and J Dilla association.', false),
('Smino', 'Christopher Smith Jr.', 'St. Louis, Missouri', 1991, 10, 2, 'St. Louis rapper known for his melodic style and R&B influences.', false),
('Soulja Boy', 'DeAndre Cortez Way', 'Chicago, Illinois', 1990, 7, 28, 'Chicago rapper known for his viral internet success and dance crazes.', false),
('Souls of Mischief', null, 'Oakland, California', null, null, null, 'Oakland rap group known for their alternative hip hop style and Hieroglyphics collective.', false),
('Styles P', 'David R. Styles', 'Corona, Queens', 1974, 11, 28, 'Queens rapper known for his LOX membership and hardcore street style.', false),
('Talib Kweli', 'Talib Kweli Greene', 'Brooklyn, New York', 1975, 10, 3, 'Brooklyn rapper known for his conscious lyrics and Black Star collaboration.', false),
('Tech N9ne', 'Aaron Dontez Yates', 'Kansas City, Missouri', 1971, 11, 8, 'Missouri rapper known for his rapid-fire delivery and independent success.', false),
('The D.O.C.', 'Tracy Lynn Curry', 'Dallas, Texas', 1968, 6, 10, 'Texas rapper known for his N.W.A association and influential debut album.', false),
('The Fugees', null, 'South Orange, New Jersey', null, null, null, 'New Jersey rap group known for their conscious lyrics and diverse musical influences.', false),
('The Game', 'Jayceon Terrell Taylor', 'Compton, California', 1979, 11, 29, 'Compton rapper known for his West Coast style and Aftermath Entertainment association.', false),
('The Pharcyde', null, 'South Central Los Angeles', null, null, null, 'Los Angeles rap group known for their alternative hip hop style and creative videos.', false),
('Three 6 Mafia', null, 'Memphis, Tennessee', null, null, null, 'Memphis rap group known for their dark production style and crunk influence.', false),
('Tierra Whack', 'Tierra Helena Whack', 'Philadelphia, Pennsylvania', 1995, 8, 11, 'Philadelphia rapper known for her creative visuals and experimental approach.', false),
('Tobe Nwigwe', 'Tobe Nwigwe', 'Houston, Texas', 1987, 3, 8, 'Houston rapper known for his conscious lyrics and Nigerian heritage.', false),
('Too $hort', 'Todd Anthony Shaw', 'Los Angeles, California', 1966, 4, 28, 'California rapper known for his Bay Area influence and longevity.', false),
('Trina', 'Katrina Laverne Taylor', 'Miami, Florida', 1978, 12, 3, 'Miami rapper known for her Southern style and female empowerment themes.', false),
('Twista', 'Carl Terrell Mitchell', 'Chicago, Illinois', 1973, 11, 27, 'Chicago rapper known for his rapid-fire delivery and Midwest sound.', false),
('UGK', null, 'Port Arthur, Texas', null, null, null, 'Texas rap duo known for their Southern rap influence and country rap sound.', false),
('Uncle Murda', 'Leonard Grant', 'Brooklyn, New York', 1980, 7, 25, 'Brooklyn rapper known for his street narratives and annual rap up songs.', false),
('Waka Flocka Flame', 'Juaquin James Malphurs', 'South Jamaica, Queens', 1986, 5, 31, 'Queens-born rapper known for his crunk style and Atlanta association.', false),
('Wale', 'Olubowale Victor Akintimehin', 'Washington, D.C.', 1984, 9, 21, 'D.C. rapper known for his conscious lyrics and go-go music influences.', false),
('Webbie', 'Webster Gradney Jr.', 'Baton Rouge, Louisiana', 1985, 9, 6, 'Louisiana rapper known for his Southern style and Trill Entertainment association.', false),
('Westside Boogie', 'Anthony Tremaine Dixson', 'Compton, California', 1989, 8, 30, 'Compton rapper known for his introspective lyrics and West Coast sound.', false),
('Westside Gunn', 'Alvin Lamar Worthy', 'Buffalo, New York', 1982, 7, 27, 'Buffalo rapper known for his Griselda Records leadership and boom bap style.', false),
('Will Smith', 'Willard Carroll Smith Jr.', 'Philadelphia, Pennsylvania', 1968, 9, 25, 'Philadelphia rapper known for his positive messages and crossover success.', false),
('Wu-Tang Clan', null, 'Staten Island, New York', null, null, null, 'Staten Island rap group known for their martial arts influence and innovative approach.', false),
('XXXTENTACION', 'Jahseh Dwayne Ricardo Onfroy', 'Plantation, Florida', 1998, 1, 23, 'Florida rapper known for his emotional style and controversial persona.', false),
('Xzibit', 'Alvin Nathaniel Joiner', 'Detroit, Michigan', 1974, 9, 18, 'Detroit rapper known for his West Coast association and "Pimp My Ride" hosting.', false),
('Yeat', 'Noah Olivier Smith', 'Irvine, California', 2000, 2, 26, 'California rapper known for his melodic trap style and internet popularity.', false),
('Yelawolf', 'Michael Wayne Atha', 'Gadsden, Alabama', 1979, 12, 30, 'Alabama rapper known for his country rap style and rock influences.', false),
('YG', 'Keenon Dequan Ray Jackson', 'Compton, California', 1990, 3, 9, 'Compton rapper known for his West Coast style and Bloods association.', false),
('Young M.A', 'Katorah Kasanova Marrero', 'Brooklyn, New York', 1992, 4, 3, 'Brooklyn rapper known for her LGBTQ+ representation and drill-influenced style.', false),
('Yung Miami', 'Caresha Romeka Brownlee', 'Miami, Florida', 1994, 2, 11, 'Miami rapper known for her City Girls membership and Southern hip hop style.', false)
ON CONFLICT (name) DO NOTHING;
