// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzcmkssadekswmiqfbff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y21rc3NhZGVrc3dtaXFmYmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjQ0NDksImV4cCI6MjA2MzY0MDQ0OX0.j8BSOA66HYYFHg73ntnewGSf9xByQZ-9PHlR2JTRNQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);